@startuml

class Account {
  - id: int
  - email: String
  - password: String
}
class Address {
  - id: int
  - street: String
  - zipCode: String
  - city: String
  - country: String
}
class Category {
  - id: int
  - name: String
  - description: String
}
class Item {
  - id: int
  - name: String
  - sku: String
  - description: String
  - price: double
  - category: Category
}
class Merchant {
  - id: int
  - name: String
  - email: String
}
class MerchantOrder {
  - id: int
  - orderDate: LocalDateTime
}
class Order {
  - id: int
  - orderDate: LocalDateTime
  - user: User
}
class Payment {
  - id: int
  - amount: double
  - paymentDateTime: LocalDateTime
}
class ShippingOrder {
  - id: int
  - shippingOrderDate: LocalDateTime
}
class User {
  - id: int
  - firstname: String
  - lastname: String
}
interface IValueObject << interface >>
class ItemQuantity {
  - id: int
}
class OrderQuantity {
  - quantity: int
}
class StockQuantity {
  - quantity: int
}
enum MerchantOrderStatusEnum << enumeration >> {
  + APPROVED:
  + DELIVERED:
  + PENDING:
  + REJECTED:
  + SHIPPED:
}
enum OrderStatusEnum << enumeration >> {
  + PENDING:
  + APPROVED:
  + REJECTED:
  + DELIVERED:
  + SHIPPED:
}
enum PaymentMethodEnum << enumeration >> {
  + PAYPAL:
  + CARD:
}
enum PaymentStatusEnum << enumeration >> {
  + ACCEPTED:
  + PENDING:
  + REJECTED:
}
enum RoleEnum << enumeration >> {
  + ADMIN:
  + USER:
  + MERCHANT:
}
enum ShippingOrderStatusEnum << enumeration >> {
  + REJECTED:
  + APPROVED:
  + DELIVERED:
  + SHIPPED:
  + PENDING:
}

Account                 "1" *-> "role\n1" RoleEnum
Address                 "*" *-right> "user\n1" User
Item                    "1" *-left> "category\n1" Category
Item                    "1" *-left> "merchant\n1" Merchant
Item                    "1" *--> "quantityInStock\n1" StockQuantity
ItemQuantity            "*" *-left> "item\n1" Item
ItemQuantity            "1" *-> "quantityOrdered\n1" OrderQuantity
Merchant                "1" *-up-> "address\n1" Address
MerchantOrder           "1" *-down-> "merchant\n1" Merchant
MerchantOrder           "1" *-left> "status\n1" MerchantOrderStatusEnum
MerchantOrder           "1" *-up-> "order\n1" Order
MerchantOrder           "1" *-down-> "user\n1" User
Order                   "1" *-> "itemQuantities\n*" ItemQuantity
Order                   "1" *-> "status\n1" OrderStatusEnum
Order                   "1" *-up-> "payment\n1" Payment
Order                   "1" *-down-> "user\n1" User
Payment                 "1" *-> "paymentMethod\n1" PaymentMethodEnum
Payment                 "1" *-> "status\n1" PaymentStatusEnum
ShippingOrder           "1" *-down-> "shippingAddress\n1" Address
ShippingOrder           "1" *-left> "merchantOrder\n1" MerchantOrder
ShippingOrder           "1" *-up-> "order\n1" Order
ShippingOrder           "1" *-> "status\n1" ShippingOrderStatusEnum
ShippingOrder           "1" *-down-> "user\n1" User
User                    "1" *-right-> "account\n1" Account
OrderQuantity            --^  IValueObject
StockQuantity            --^  IValueObject
@enduml
