apiVersion: v1
kind: Namespace
metadata:
  name: retailproject-namespace
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: retailproject-order-read-deployment
  namespace: retailproject-namespace
spec:
  selector:
    matchLabels:
      app: retailproject-orders-read
  replicas: 1
  template:
    metadata:
      labels:
        app: retailproject-orders-read
    spec:
      containers:
        - name: order-read-retailproject-container
          image: order-read-retailproject_service
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: 100m
              memory: 512Mi
            limits:
              cpu: 250m
              memory: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: retailproject-order-read-service
  namespace: retailproject-namespace
spec:
  selector:
    app: retailproject-orders-read
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      nodePort: 30021
  type: NodePort
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: retailproject-order-read-service-hpa
  namespace: retailproject-namespace
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: retailproject-order-read-deployment
  minReplicas: 1
  maxReplicas: 3
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70