apiVersion: v1
kind: Namespace
metadata:
  name: retailproject-namespace
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: retailproject-apigateway-deployment
  namespace: retailproject-namespace
spec:
  selector:
    matchLabels:
      app: serviceregistry
  replicas: 1
  template:
    metadata:
      labels:
        app: serviceregistry
    spec:
      containers:
        - name: apigatewayapplication-retailproject-container
          image: apigatewayapplication-retailproject_service
          imagePullPolicy: Never
          ports:
            - containerPort: 8761
---
apiVersion: v1
kind: Service
metadata:
  name: retailproject-apigateway-service
  namespace: retailproject-namespace
spec:
  selector:
    app: serviceregistry
  ports:
    - name: http
      port: 8761
      targetPort: 8761
      nodePort: 30001
  type: NodePort