{
 "title": "Kepler DIMEI test",
 "description": "Dashboard for Kepler Exporter",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(kepler_container_cpu_joules_total,namespace)"
    }
   },
   {
    "name": "pod",
    "label": "Pod",
    "query": {
     "query": "label_values(kepler_container_cpu_joules_total{namespace=~\"$namespace\"},pod)"
    }
   },
   {
    "name": "container_name",
    "label": "Container_name",
    "query": {
     "query": "label_values(kepler_container_cpu_joules_total{namespace=~\"$namespace\"},container_name)"
    }
   },
   { "name": "coal", "label": "Coal Coeff", "query": "2.23" },
   { "name": "natural_gas", "label": "Natural Gas Coeff", "query": "0.91" },
   { "name": "petroleum", "label": "Petroleum Coeff", "query": "2.13" },
   { "name": "watt_per_second_to_kWh", "query": "${VAR_WATT_PER_SECOND_TO_KWH}" }
  ]
 },
 "panels": [
  { "title": "Carbon Emissions", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Carbon Footprint (pounds per kWh per day) in Namespace: $namespace  (PKG+CORE)",
   "type": "gauge",
   "description": "Using CO2 emissions  by power generation type as reported by US Energy Information Administration https://www.eia.gov/tools/faqs/faq.php?id=74&t=11",
   "gridPos": { "h": 6, "w": 19, "x": 1, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "( sum(\n      increase(\n         (kepler_container_cpu_joules_total{container_namespace=~\"$namespace\", pod_name=~\"$pod\", container_name=\"$container_name\"}[$__range])\n      )\n   ) * $watt_per_second_to_kWh \n) * $coal",
     "legendFormat": "CO2 Coal"
    },
    {
     "expr": "( sum(\n      increase(\n         (kepler_container_cpu_joules_total{container_namespace=~\"$namespace\", pod_name=~\"$pod\", container_name=\"$container_name\"}[$__range])\n      )\n   ) * $watt_per_second_to_kWh \n) * $petroleum",
     "legendFormat": "CO2 Petroleum"
    },
    {
     "expr": "( sum(\n      increase(\n         (kepler_container_cpu_joules_total{container_namespace=~\"$namespace\", pod_name=~\"$pod\", container_name=\"$container_name\"}[$__range])\n      )\n   ) * $watt_per_second_to_kWh \n) * $natural_gas",
     "legendFormat": "CO2 Natural Gas"
    }
   ]
  },
  { "title": "Power Consumption", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Pod/Process Power Consumption (W) in Namespace: $namespace",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum by (container_name) (irate(kepler_container_cpu_joules_total{container_namespace=~\"$namespace\", pod_name=~\"$pod\", container_name=\"$container_name\", zone=\"package\"}[$__range]))",
     "legendFormat": "$container_name / PKG"
    },
    {
     "expr": "sum by (container_name) (irate(kepler_container_cpu_joules_total{container_namespace=~\"$namespace\", pod_name=~\"$pod\", container_name=\"$container_name\", zone=\"core\"}[$__range]))",
     "legendFormat": "$container_name / CORE"
    }
   ]
  },
  {
   "title": "Total Power Consumption (W) in Namespace: $namespace",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "sum(irate(kepler_container_cpu_joules_total{container_namespace=~\"$namespace\", pod_name=~\"$pod\", container_name=\"$container_name\", zone=\"package\"}[$__range]))",
     "legendFormat": "PKG"
    },
    {
     "expr": "sum(irate(kepler_container_cpu_joules_total{container_namespace=~\"$namespace\", pod_name=~\"$pod\", container_name=\"$container_name\", zone=\"core\"}[$__range]))",
     "legendFormat": "CORE"
    }
   ]
  },
  {
   "title": "$container_name",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "targets": [
    {
     "expr": "sum (\n  increase(\n   (kepler_container_cpu_joules_total{container_namespace=~\"$namespace\", pod_name=~\"$pod\", container_name=\"$container_name\", zone=\"package\"}[$__range])\n  )\n) * $watt_per_second_to_kWh",
     "legendFormat": "PKG"
    },
    {
     "expr": "sum (\n  increase(\n   (kepler_container_cpu_joules_total{container_namespace=~\"$namespace\", pod_name=~\"$pod\", container_name=\"$container_name\", zone=\"core\"}[$__range])\n  )\n) * $watt_per_second_to_kWh",
     "legendFormat": "CORE"
    }
   ]
  },
  {
   "title": "Total Power Consumption (PKG+CORE) by Namespace (kWh per day)",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 26 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (container_namespace, pod_name, container_name) (\n  increase(\n      (kepler_container_cpu_joules_total{container_namespace=~\"$namespace\", pod_name=~\"$pod\", container_name=\"$container_name\"}[$__range])\n  )\n) * $watt_per_second_to_kWh ",
     "legendFormat": "{{container_namespace}}"
    }
   ]
  }
 ]
}